# Site settings

title: Vic Yeh # Title of your site
email: vic.yeh@ucla.edu # Your contant email

description: > # this means to ignore newlines until "baseurl:"
  Just a blog of another college student.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vicyeh.com" # the base hostname & protocol for your site

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

twitter_username:     vicohyeh  # Replace this with your Twitter username
github_username:      vic317yeh  # Replace this with your GitHub username

# Build settings
markdown: kramdown
highlighter: rouge
